version: '3'

x-prop:
  &docker-properties
  container_name: "Resume-Latex"
  entrypoint: pdflatex
  volumes:
    - ../resume:/data

services:
  resume:
    # -- Running local image
    image: vcaln/docker-resume:latest
    <<: *docker-properties
  #
  # Pushing to Docker-hub
  public:
    build:
      context: ../
      dockerfile: ./docker/resume.Dockerfile
    # -- Running local image
    image: vcaln/docker-resume:latest
    <<: *docker-properties
