name: Resume Builder
run-name: ${{ github.actor }} - Resume
on: [push]
jobs:
  Victor_Calderon:
    runs-on: "ubuntu-latest"
    env:
      NAME: Victor_F_Calderon
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose Setup
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.3.3 # defaults to 'latest'
          legacy: true # will also install in PATH as `docker-compose`
      - name: Build Docker image
        run: make build
      - name: Create Resume
        run: make run

      # - name: Update file in repository
      #   run: |
      #     mkdir -p ./final_resumes/${NAME}
      #     cp ./resume/${NAME}/${NAME}.pdf ./final_resumes/${NAME}
      #     git add ./final_resumes/${NAME}/${NAME}.pdf
      # - name: setup git config
      #   run: |
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"
      # - name: commit
      #   run: |
      #     # Stage the file, commit and push
      #     git add time.txt
      #     git commit -m "new date commit"
      #     git push origin master
      - uses: actions/upload-artifact@v3
        with:
          name: Victor-Calderon-Resume
          path: ./resume/${NAME}/${NAME}.pdf
