# Main environment
env:
  PERSON_NAME: Victor_F_Calderon
  DOCKER_COMPOSE_VERSION: v2.3.3

name: Resume Builder
run-name: ${{ github.actor }} - Resume
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"
jobs:
  #
  # --- Linting code
  lint-code:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      # Install Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      # Install Python dependencies
      - name: Install dependencies
        run: |
          make requirements
          make pre-commit-install
          make lint
  #
  # ---- Build Latex PDF and upload to repo's Github Pages
  build-latex-locally:
    runs-on: "ubuntu-latest"
    needs: lint-code
    steps:
      # Checkout out the repository
      - uses: actions/checkout@v3
      # Add variable to environment variables
      - name: Add variables
        run: |
          echo "INPUT_FILE_PATH='./resume/${PERSON_NAME}/${PERSON_NAME}_Resume.pdf'" >> $GITHUB_ENV
          echo "ARTIFACT_NAME='${PERSON_NAME}_Resume'" >> $GITHUB_ENV
          cat $GITHUB_ENV
      # Install the necessary version of 'docker-compose'
      - name: Docker Compose Setup
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: ${DOCKER_COMPOSE_VERSION} # defaults to 'latest'
          legacy: true # will also install in PATH as `docker-compose`
      # Create PDF with specified file
      - name: Create Resume
        run: |
          make \
          PERSON_NAME="${PERSON_NAME}" \
          run
      # Copy resume into resulting output directory
      - name: Rearrange files
        run: |
          echo "Name: ${PERSON_NAME}"
          rm .gitignore
          touch .nojekyll
          [ -f ${{ env.INPUT_FILE_PATH }} ] && echo "${{ env.INPUT_FILE_PATH }} exist." || echo "${{ env.INPUT_FILE_PATH }} does not exist."
          mkdir -p pdf
          cp ${{ env.INPUT_FILE_PATH }} pdf/
      # Upload artifact to Job
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: pdf/*.pdf
      # Deploy PDF to Github pages
      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdf
          force_orphan: true
